language: python
python:
  - "2.7"
before_install:
  - pip install pytest pytest-cov
  - pip install coveralls
  - sudo apt-get install -y gfortran
before_script:
  - cd tests
script:
  - ./run_tests.sh
after_success:
  - cd Qpyl
  - coveralls
