language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
before_install:
  - pip install -U pytest pytest-cov
  - pip install -U coveralls
  - sudo apt-get install -y gfortran
before_script:
  - cd tests
script:
  - ./run_tests.sh
after_success:
  - cd Qpyl
  - coveralls
